---

- name: common - reload iptables
  command: iptables-restore /etc/sysconfig/iptables
  tags:
    - notest

- name: common - reload ip6tables
  command: ip6tables-restore /etc/sysconfig/ip6tables
  tags:
    - notest
