---
galaxy_info:
  role_name: common
  author: Lev Goncharov
  description: Ansible role for installing common things and demo

  license: MIT

  min_ansible_version: 1.2

  galaxy_tags:
    - centos

  platforms:
    - name: Centos
      versions:
        - 7.6
