---
- name: Required software are installed
  yum:
    name: "{{ game2048__software }}"
    state: present

- name: iptables rules are installed
  template:
    src: "{{ game2048__iptables_item }}.j2"
    dest: "/etc/sysconfig/{{ game2048__iptables_item }}"
    force: true
    validate: "/sbin/{{ game2048__iptables_item }}-restore --test %s"
  loop:
    - iptables
    - ip6tables
  loop_control:
    loop_var: game2048__iptables_item
  notify:
    - game2048 reload iptables
    - game2048 reload ip6tables

- name: Repo is checked out
  git:
    repo: https://github.com/ultral/2048.git
    dest: /var/www/html
    force: true
    version: HEAD

- name: Httpd is started
  systemd:
    name: httpd
    enabled: true
    state: started
    daemon_reload: true

- name: Print message
  debug:
    msg: "Site locates at http://localhost:8080/"
